language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t omvk97/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true omvk97/react-test npm test

after_success:
  - docker build -t omvk97/multi-client ./client
  - docker build -t omvk97/multi-nginx ./nginx
  - docker build -t omvk97/multi-server ./server
  - docker build -t omvk97/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push omvk97/multi-client
  - docker push omvk97/multi-nginx
  - docker push omvk97/multi-server
  - docker push omvk97/multi-worker
